### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by davidarchi** [nicholasrout/lens-launcher#23]
I faced issue when run code 
Could you help to check

> 02-18 15:31:03.190 27242-27242/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: nickrout.lenslauncher, PID: 27242
                                                   android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
                                                   #################################################################
                                                   Error Code : 1 (SQLITE_ERROR)
                                                   Caused By : SQL(query) error or missing database.
                                                   	(no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
                                                   #################################################################
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
                                                       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1378)
                                                       at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                       at com.orm.query.Select.first(Select.java:154)
                                                       at nickrout.lenslauncher.model.AppPersistent.getAppVisibility(AppPersistent.java:129)
                                                       at nickrout.lenslauncher.adapter.AppRecyclerAdapter$AppViewHolder.setAppElement(AppRecyclerAdapter.java:108)
                                                       at nickrout.lenslauncher.adapter.AppRecyclerAdapter.onBindViewHolder(AppRecyclerAdapter.java:74)
                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                       at android.view.View.layout(View.java:17938)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                       at android.view.View.layout(View.java:17938)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                       at android.view.View.layout(View.java:17938)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                   	at an
02-18 15:31:55.790 29018-29018/nickrout.lenslauncher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: nickrout.lenslauncher, PID: 29018
                                                                       java.lang.RuntimeException: Unable to start receiver nickrout.lenslauncher.background.BroadcastReceivers$AppsLoadedReceiver: android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
                                                                       #################################################################
                                                                       Error Code : 1 (SQLITE_ERROR)
                                                                       Caused By : SQL(query) error or missing database.
                                                                       	(no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
                                                                       #################################################################
                                                                           at android.app.ActivityThread.handleReceiver(ActivityThread.java:3641)
                                                                           at android.app.ActivityThread.access$2000(ActivityThread.java:221)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
                                                                       #################################################################
                                                                       Error Code : 1 (SQLITE_ERROR)
                                                                       Caused By : SQL(query) error or missing database.
                                                                       	(no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
                                                                       #################################################################
                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
                                                                           at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1378)
                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                           at com.orm.query.Select.first(Select.java:154)
                                                                           at nickrout.lenslauncher.model.AppPersistent.getAppVisibility(AppPersistent.java:129)
                                                                           at nickrout.lenslauncher.ui.HomeActivity.removeHiddenApps(HomeActivity.java:106)
                                                                           at nickrout.lenslauncher.ui.HomeActivity.assignApps(HomeActivity.java:100)
                                                                           at nickrout.lenslauncher.ui.HomeActivity.update(HomeActivity.java:129)
                                                                           at java.util.Observable.notifyObservers(Observable.java:138)
                                                                           at nickrout.lenslauncher.background.LoadedObservable.updateValue(LoadedObservable.java:21)
                                                                           at nickrout.lenslauncher.background.LoadedObservable.update(LoadedObservable.java:26)
                                                                           at nickrout.lenslauncher.background.BroadcastReceivers$AppsLoadedReceiver.onReceive(BroadcastReceivers.java:36)
                                                                           at android.app.ActivityThread.handleReceiver(ActivityThread.java:3634)
                                                                           	... 8 more
02-18 15:34:30.090 31958-31958/com.fast.textoverlay.network E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.fast.textoverlay.network, PID: 31958
                                                                              java.lang.RuntimeException: Unable to create service saschpe.textoverlay.service.TextOverlayService: java.lang.SecurityException: com.fast.textoverlay.network from uid 10408 not allowed to perform SYSTEM_ALERT_WINDOW
                                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3817)
                                                                                  at android.app.ActivityThread.access$2100(ActivityThread.java:221)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                               Caused by: java.lang.SecurityException: com.fast.textoverlay.network from uid 10408 not allowed to perform SYSTEM_ALERT_WINDOW
                                                                                  at android.os.Parcel.readException(Parcel.java:1620)
                                                                                  at android.os.Parcel.readException(Parcel.java:1573)
                                                                                  at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:791)
                                                                                  at android.view.ViewRootImpl.setView(ViewRootImpl.java:813)
                                                                                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
                                                                                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                                  at saschpe.textoverlay.service.TextOverlayService.onCreate(Unknown Source)
                                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
                                                                                  at android.app.ActivityThread.access$2100(ActivityThread.java:221) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:158) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
02-18 15:34:35.675 32141-32141/com.fast.textoverlay.network E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.fast.textoverlay.network, PID: 32141
                                                                              java.lang.RuntimeException: Unable to create service saschpe.textoverlay.service.TextOverlayService: java.lang.SecurityException: com.fast.textoverlay.network from uid 10408 not allowed to perform SYSTEM_ALERT_WINDOW
                                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3817)
                                                                                  at android.app.ActivityThread.access$2100(ActivityThread.java:221)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                               Caused by: java.lang.SecurityException: com.fast.textoverlay.network from uid 10408 not allowed to perform SYSTEM_ALERT_WINDOW
                                                                                  at android.os.Parcel.readException(Parcel.java:1620)
                                                                                  at android.os.Parcel.readException(Parcel.java:1573)
                                                                                  at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:791)
                                                                                  at android.view.ViewRootImpl.setView(ViewRootImpl.java:813)
                                                                                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
                                                                                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                                  at saschpe.textoverlay.service.TextOverlayService.onCreate(Unknown Source)
                                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
                                                                                  at android.app.ActivityThread.access$2100(ActivityThread.java:221) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:158) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
02-18 15:39:41.205 2420-2420/nickrout.lenslauncher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: nickrout.lenslauncher, PID: 2420
                                                                     android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
                                                                     #################################################################
                                                                     Error Code : 1 (SQLITE_ERROR)
                                                                     Caused By : SQL(query) error or missing database.
                                                                     	(no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
                                                                     #################################################################
                                                                         at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                         at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                                         at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                                         at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                         at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                         at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                         at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                         at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
                                                                         at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
                                                                         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
                                                                         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1378)
                                                                         at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                         at com.orm.query.Select.first(Select.java:154)
                                                                         at nickrout.lenslauncher.model.AppPersistent.getAppVisibility(AppPersistent.java:129)
                                                                         at nickrout.lenslauncher.adapter.AppRecyclerAdapter$AppViewHolder.setAppElement(AppRecyclerAdapter.java:108)
                                                                         at nickrout.lenslauncher.adapter.AppRecyclerAdapter.onBindViewHolder(AppRecyclerAdapter.java:74)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                         at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                         at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                     	at and
02-18 15:43:01.790 5174-5174/nickrout.lenslauncher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: nickrout.lenslauncher, PID: 5174
                                                                     android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
                                                                     #################################################################
                                                                     Error Code : 1 (SQLITE_ERROR)
                                                                     Caused By : SQL(query) error or missing database.
                                                                     	(no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
                                                                     #################################################################
                                                                         at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                         at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                                         at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                                         at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                         at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                         at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                         at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                         at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
                                                                         at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
                                                                         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
                                                                         at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1378)
                                                                         at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                         at com.orm.query.Select.first(Select.java:154)
                                                                         at nickrout.lenslauncher.model.AppPersistent.getAppVisibility(AppPersistent.java:129)
                                                                         at nickrout.lenslauncher.adapter.AppRecyclerAdapter$AppViewHolder.setAppElement(AppRecyclerAdapter.java:108)
                                                                         at nickrout.lenslauncher.adapter.AppRecyclerAdapter.onBindViewHolder(AppRecyclerAdapter.java:74)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                         at android.view.View.layout(View.java:17938)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                         at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                         at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                         at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                     	at and

**Comment by nicholasrout** [comment]
Hi @davidarchi,

This is an issue with SugarORM. Try uninstalling the app, disabling Instant Run in Android Studio and running again. I believe this will solve your issue.

**Comment by davidarchi** [comment]
it was resolved.
thank you
